<?xml version="1.0"?>
	<!DOCTYPE recetas [
	<!ELEMENT seccion (nombreSeccion, receta*)>
		<!ELEMENT nombreSeccion (#PCDATA)>
		<!ELEMENT receta (nombre, ingredientes, porcion, descripcion)>
			<!ELEMENT nombre (#PCDATA)>
			<!ELEMENT ingredientes (ingrediente*)>
				<!ELEMENT ingrediente (#PCDATA)>
			<!ELEMENT descripcion (lista*)>
				<!ELEMENT listaNum (#PCDATA)>
]>

<recetas>
	<seccion>
		<nombreSeccion>Apetitosos Pasteees</nombreSeccion>
		<receta>
			<nombre>Pastel de queso</nombre>
			<ingredientes>
				<ingrediente>Pan cortado en rebanadas 1/2kg</ingrediente>
				<ingrediente>Huevos 6</ingrediente>
				<ingrediente>Leche 6 tazas</ingrediente>
				<ingrediente>Queso rallado o ricota 2 tazas</ingrediente>
				<ingrediente>Cebolla picada 1 cucharada</ingrediente>
				<ingrediente>Sal cantidad necesaria</ingrediente>
				<ingrediente>Pimienta 2 cucharaditas</ingrediente>
			</ingredientes>
			<descripcion>
				<listaNum>
					1.	En una asadera enmantecada se coloca, en el fondo, una camada de rebanadas de pan, se espolvorean con abundante queso rallado y se vuelve a poner otra camada de rebanadas de pan que se cubre con el queso restante.
				</listaNum>
				<listaNum>
					2.	Aparte se baten los huevos, se les agrega leche, la sal y la cebolla y se vierte este líquido sobre las rebanadas de pan y queso. Se cocina en horno moderado durante una hora más o menos.
				</listaNum>
			</descripcion>
		</receta>
		<receta>
			<nombre>Pastel de queso</nombre>
			<ingredientes>
				<ingrediente>Pan cortado en rebanadas 1/2kg</ingrediente>
				<ingrediente>Huevos 6</ingrediente>
				<ingrediente>Leche 6 tazas</ingrediente>
				<ingrediente>Queso rallado o ricota 2 tazas</ingrediente>
				<ingrediente>Cebolla picada 1 cucharada</ingrediente>
				<ingrediente>Sal cantidad necesaria</ingrediente>
				<ingrediente>Pimienta 2 cucharaditas</ingrediente>
			</ingredientes>
			<descripcion>
				<listaNum>
					1.	En una asadera enmantecada se coloca, en el fondo, una camada de rebanadas de pan, se espolvorean con abundante queso rallado y se vuelve a poner otra camada de rebanadas de pan que se cubre con el queso restante.
				</listaNum>
				<listaNum>
					2.	Aparte se baten los huevos, se les agrega leche, la sal y la cebolla y se vierte este líquido sobre las rebanadas de pan y queso. Se cocina en horno moderado durante una hora más o menos.
				</listaNum>
			</descripcion>
		</receta>
		<receta>
			<nombre>Pastel de queso</nombre>
			<ingredientes>
				<ingrediente>Pan cortado en rebanadas 1/2kg</ingrediente>
				<ingrediente>Huevos 6</ingrediente>
				<ingrediente>Leche 6 tazas</ingrediente>
				<ingrediente>Queso rallado o ricota 2 tazas</ingrediente>
				<ingrediente>Cebolla picada 1 cucharada</ingrediente>
				<ingrediente>Sal cantidad necesaria</ingrediente>
				<ingrediente>Pimienta 2 cucharaditas</ingrediente>
			</ingredientes>
			<descripcion>
				<listaNum>
					1.	En una asadera enmantecada se coloca, en el fondo, una camada de rebanadas de pan, se espolvorean con abundante queso rallado y se vuelve a poner otra camada de rebanadas de pan que se cubre con el queso restante.
				</listaNum>
				<listaNum>
					2.	Aparte se baten los huevos, se les agrega leche, la sal y la cebolla y se vierte este líquido sobre las rebanadas de pan y queso. Se cocina en horno moderado durante una hora más o menos.
				</listaNum>
			</descripcion>
		</receta>
		
	</seccion>
</recetas>